# Generated by Django 5.1.3 on 2024-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('instructions', models.IntegerField()),
                ('ingredients', models.IntegerField()),
                ('time', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('kcal', models.IntegerField()),
                ('imageurl', models.CharField(max_length=1000)),
                ('user', models.IntegerField()),
            ],
        ),
    ]
